export class RepoNotFoundAutoCreateEdgeCase {
  public static async handle404(
    authHeaders: Record<string, string>,
    repoName: string,
    isPrivate: boolean
  ): Promise<{ success: boolean; repoUrl?: string; error?: string }> {
    try {
      const res = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: authHeaders,
        body: JSON.stringify({
          name: repoName,
          private: isPrivate,
          auto_init: true,
          description: "Generated by Pipeline Management OpenVSCode IDE",
        }),
      });

      if (!res.ok) {
        const text = await res.text();
        return { success: false, error: `Failed auto-creating GitHub repository: ${text}` };
      }

      const data = await res.json();
      return { success: true, repoUrl: data.html_url };
    } catch (err: any) {
      return { success: false, error: err.message || "Failed auto-creating repository" };
    }
  }
}
