/**
 * ALGORITHM: GITHUB REST GIT DATA API FALLBACK PIPELINE
 * ============================================================================
 * 1. SHARED HTTP FACADE (`requestGitHubApi`):
 *    - Encapsulates base URL `https://api.github.com`, auth headers, and JSON request/response handling.
 * 
 * 2. REPOSITORY INITIALIZATION (`ensureRepositoryExists`):
 *    - Checks repository status (`GET /repos/{owner}/{repo}`).
 *    - Auto-creates repository if HTTP 404 returned (`POST /user/repos`).
 * 
 * 3. BRANCH BASE POINTER RESOLUTION (`fetchBranchDetails`):
 *    - Resolves base commit SHA and tree SHA (`GET /repos/{owner}/{repo}/branches/{branch}`).
 * 
 * 4. GIT TREE CREATION (`createGitTree`):
 *    - Creates remote tree containing workspace additions (`POST /repos/{owner}/{repo}/git/trees`).
 * 
 * 5. GIT COMMIT CREATION (`createGitCommit`):
 *    - Creates commit object pointing to new tree SHA (`POST /repos/{owner}/{repo}/git/commits`).
 * 
 * 6. BRANCH REF UPDATE & CREATION (`updateOrCreateBranchRef`):
 *    - Updates branch pointer via `PATCH /git/refs/heads/{branch}`.
 *    - Falls back to `POST /git/refs` if branch reference does not exist yet.
 * ============================================================================
 */

import type { FlatFileEntry } from "./tree-flattening.service";

export interface RestCommitParams {
  authHeaders: Record<string, string>;
  owner: string;
  repo: string;
  branch: string;
  commitMessage: string;
  authenticatedUser: string;
  isPrivate: boolean;
  filesToCommit: FlatFileEntry[];
}

export interface RestCommitResult {
  success: boolean;
  shortHash?: string;
  fullHash?: string;
  repoUrl?: string;
  error?: string;
  repoCreated?: boolean;
}

export class GitHubRestFallbackService {
  private static readonly GITHUB_API_BASE = "https://api.github.com";

  private static async requestGitHubApi(
    path: string,
    method: "GET" | "POST" | "PATCH",
    headers: Record<string, string>,
    body?: unknown
  ): Promise<{ ok: boolean; status: number; data?: any; errorText?: string }> {
    try {
      const url = `${this.GITHUB_API_BASE}${path}`;
      const res = await fetch(url, {
        method,
        headers,
        body: body ? JSON.stringify(body) : undefined,
      });

      if (!res.ok) {
        const errorText = await res.text();
        return { ok: false, status: res.status, errorText };
      }

      const data = await res.json().catch(() => ({}));
      return { ok: true, status: res.status, data };
    } catch (err: any) {
      return { ok: false, status: 500, errorText: err.message || "Network error" };
    }
  }

  private static async ensureRepositoryExists(
    headers: Record<string, string>,
    owner: string,
    repo: string,
    isPrivate: boolean
  ): Promise<{ repoUrl: string; repoCreated: boolean; error?: string }> {
    const check = await this.requestGitHubApi(`/repos/${owner}/${repo}`, "GET", headers);
    let defaultRepoUrl = `https://github.com/${owner}/${repo}`;

    if (check.status === 404) {
      const createRes = await this.requestGitHubApi("/user/repos", "POST", headers, {
        name: repo,
        private: isPrivate,
        auto_init: true,
        description: "Generated by Pipeline Management OpenVSCode IDE",
      });

      if (!createRes.ok) {
        return { repoUrl: defaultRepoUrl, repoCreated: false, error: `Failed to create repo: ${createRes.errorText}` };
      }

      await new Promise((resolve) => setTimeout(resolve, 1500));
      return { repoUrl: createRes.data?.html_url || defaultRepoUrl, repoCreated: true };
    }

    return { repoUrl: check.data?.html_url || defaultRepoUrl, repoCreated: false };
  }

  private static async fetchBranchDetails(
    headers: Record<string, string>,
    owner: string,
    repo: string,
    branch: string
  ): Promise<{ baseCommitSha: string | null; baseTreeSha: string | null }> {
    const branchRes = await this.requestGitHubApi(`/repos/${owner}/${repo}/branches/${branch}`, "GET", headers);
    if (branchRes.ok && branchRes.data?.commit) {
      return {
        baseCommitSha: branchRes.data.commit.sha,
        baseTreeSha: branchRes.data.commit.commit.tree.sha,
      };
    }

    const refsRes = await this.requestGitHubApi(`/repos/${owner}/${repo}/git/matching-refs/heads/`, "GET", headers);
    if (refsRes.ok && Array.isArray(refsRes.data) && refsRes.data.length > 0) {
      return {
        baseCommitSha: refsRes.data[0].object.sha,
        baseTreeSha: null,
      };
    }

    return { baseCommitSha: null, baseTreeSha: null };
  }

  private static async createGitTree(
    headers: Record<string, string>,
    owner: string,
    repo: string,
    baseTreeSha: string | null,
    filesToCommit: FlatFileEntry[]
  ): Promise<{ treeSha?: string; error?: string }> {
    const treeEntries = filesToCommit.map((f) => ({
      path: f.path.replace(/^\/+/, ""),
      mode: "100644",
      type: "blob",
      content: f.content,
    }));

    const res = await this.requestGitHubApi(`/repos/${owner}/${repo}/git/trees`, "POST", headers, {
      base_tree: baseTreeSha || undefined,
      tree: treeEntries,
    });

    if (!res.ok) {
      return { error: `Failed to create Git Tree: ${res.errorText}` };
    }

    return { treeSha: res.data.sha };
  }

  private static async createGitCommit(
    headers: Record<string, string>,
    owner: string,
    repo: string,
    treeSha: string,
    commitMessage: string,
    baseCommitSha: string | null
  ): Promise<{ commitSha?: string; error?: string }> {
    const res = await this.requestGitHubApi(`/repos/${owner}/${repo}/git/commits`, "POST", headers, {
      message: commitMessage,
      tree: treeSha,
      parents: baseCommitSha ? [baseCommitSha] : [],
    });

    if (!res.ok) {
      return { error: `Failed to create Git Commit: ${res.errorText}` };
    }

    return { commitSha: res.data.sha };
  }

  private static async updateOrCreateBranchRef(
    headers: Record<string, string>,
    owner: string,
    repo: string,
    branch: string,
    commitSha: string
  ): Promise<void> {
    const patchRes = await this.requestGitHubApi(`/repos/${owner}/${repo}/git/refs/heads/${branch}`, "PATCH", headers, {
      sha: commitSha,
      force: true,
    });

    if (!patchRes.ok) {
      await this.requestGitHubApi(`/repos/${owner}/${repo}/git/refs`, "POST", headers, {
        ref: `refs/heads/${branch}`,
        sha: commitSha,
      });
    }
  }

  public static async executePushPipeline(params: RestCommitParams): Promise<RestCommitResult> {
    const { authHeaders, owner, repo, branch, commitMessage, isPrivate, filesToCommit } = params;

    const repoState = await this.ensureRepositoryExists(authHeaders, owner, repo, isPrivate);
    if (repoState.error) {
      return { success: false, error: repoState.error };
    }

    const { baseCommitSha, baseTreeSha } = await this.fetchBranchDetails(authHeaders, owner, repo, branch);

    const treeState = await this.createGitTree(authHeaders, owner, repo, baseTreeSha, filesToCommit);
    if (treeState.error || !treeState.treeSha) {
      return { success: false, error: treeState.error || "Tree creation failed" };
    }

    const commitState = await this.createGitCommit(
      authHeaders,
      owner,
      repo,
      treeState.treeSha,
      commitMessage,
      baseCommitSha
    );

    if (commitState.error || !commitState.commitSha) {
      return { success: false, error: commitState.error || "Commit creation failed" };
    }

    await this.updateOrCreateBranchRef(authHeaders, owner, repo, branch, commitState.commitSha);

    const fullHash = commitState.commitSha;
    return {
      success: true,
      fullHash,
      shortHash: fullHash.substring(0, 7),
      repoUrl: `${repoState.repoUrl}/tree/${branch}`,
      repoCreated: repoState.repoCreated,
    };
  }
}
