import type { FlatFileEntry } from "./tree-flattening.service";

export interface RestCommitParams {
  authHeaders: Record<string, string>;
  owner: string;
  repo: string;
  branch: string;
  commitMessage: string;
  authenticatedUser: string;
  isPrivate: boolean;
  filesToCommit: FlatFileEntry[];
}

export interface RestCommitResult {
  success: boolean;
  shortHash?: string;
  fullHash?: string;
  repoUrl?: string;
  error?: string;
  repoCreated?: boolean;
}

export class GitHubRestFallbackService {
  public static async executePushPipeline(params: RestCommitParams): Promise<RestCommitResult> {
    const { authHeaders, owner, repo, branch, commitMessage, isPrivate, filesToCommit } = params;

    const repoCheckRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
      headers: authHeaders,
    });

    let repoCreated = false;
    let repoUrl = `https://github.com/${owner}/${repo}`;

    if (repoCheckRes.status === 404) {
      const createRepoRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: authHeaders,
        body: JSON.stringify({
          name: repo,
          private: isPrivate,
          auto_init: true,
          description: "Generated by Pipeline Management OpenVSCode IDE",
        }),
      });

      if (!createRepoRes.ok) {
        const createErr = await createRepoRes.text();
        return { success: false, error: `Failed to create GitHub repo: ${createErr}` };
      }

      const createData = await createRepoRes.json();
      repoUrl = createData.html_url || repoUrl;
      repoCreated = true;
      await new Promise((resolve) => setTimeout(resolve, 1500));
    } else if (repoCheckRes.ok) {
      const existingRepo = await repoCheckRes.json();
      repoUrl = existingRepo.html_url || repoUrl;
    }

    const branchRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/branches/${branch}`,
      { headers: authHeaders }
    );

    let baseCommitSha: string | null = null;
    let baseTreeSha: string | null = null;

    if (branchRes.ok) {
      const branchData = await branchRes.json();
      baseCommitSha = branchData.commit.sha;
      baseTreeSha = branchData.commit.commit.tree.sha;
    } else {
      const refsRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/matching-refs/heads/`,
        { headers: authHeaders }
      );
      if (refsRes.ok) {
        const refsData = await refsRes.json();
        if (Array.isArray(refsData) && refsData.length > 0) {
          baseCommitSha = refsData[0].object.sha;
          await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
            method: "POST",
            headers: authHeaders,
            body: JSON.stringify({
              ref: `refs/heads/${branch}`,
              sha: baseCommitSha,
            }),
          });
        }
      }
    }

    const treeEntries = filesToCommit.map((f) => ({
      path: f.path.replace(/^\/+/, ""),
      mode: "100644",
      type: "blob",
      content: f.content,
    }));

    const createTreeRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/trees`,
      {
        method: "POST",
        headers: authHeaders,
        body: JSON.stringify({
          base_tree: baseTreeSha || undefined,
          tree: treeEntries,
        }),
      }
    );

    if (!createTreeRes.ok) {
      const treeErr = await createTreeRes.text();
      return { success: false, error: `Failed to create Git Tree: ${treeErr}` };
    }
    const newTree = await createTreeRes.json();

    const createCommitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/commits`,
      {
        method: "POST",
        headers: authHeaders,
        body: JSON.stringify({
          message: commitMessage,
          tree: newTree.sha,
          parents: baseCommitSha ? [baseCommitSha] : [],
        }),
      }
    );

    if (!createCommitRes.ok) {
      const commitErr = await createCommitRes.text();
      return { success: false, error: `Failed to create Git Commit: ${commitErr}` };
    }
    const newCommit = await createCommitRes.json();

    await fetch(
      `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`,
      {
        method: "PATCH",
        headers: authHeaders,
        body: JSON.stringify({
          sha: newCommit.sha,
          force: true,
        }),
      }
    );

    const fullHash = newCommit.sha;
    return {
      success: true,
      fullHash,
      shortHash: fullHash.substring(0, 7),
      repoUrl: `${repoUrl}/tree/${branch}`,
      repoCreated,
    };
  }
}
