import { NextResponse } from "next/server";
import { connectToDatabase } from "@/core/database/mongodb";

interface TreeItemNode {
  id: string;
  name: string;
  type: "file" | "folder";
  path?: string;
  content?: string;
  children?: TreeItemNode[];
}

function flattenTreeItems(nodes: TreeItemNode[] = []): Array<{ path: string; content: string }> {
  let rawFiles: Array<{ path: string; content: string }> = [];

  function recurse(items: TreeItemNode[], currentPath = "") {
    for (const node of items) {
      const cleanName = node.name.replace(/\\/g, "/");
      const pathSegment = currentPath ? `${currentPath}/${cleanName}` : cleanName;

      if (node.type === "file") {
        rawFiles.push({
          path: pathSegment,
          content: node.content !== undefined ? node.content : "",
        });
      } else if (node.type === "folder" && Array.isArray(node.children)) {
        recurse(node.children, pathSegment);
      }
    }
  }

  recurse(nodes);

  if (nodes.length === 1 && nodes[0].type === "folder") {
    const rootName = nodes[0].name.replace(/\\/g, "/");
    const prefix = `${rootName}/`;
    return rawFiles.map((f) => ({
      path: f.path.startsWith(prefix) ? f.path.substring(prefix.length) : f.path,
      content: f.content,
    }));
  }

  return rawFiles;
}

export async function POST(req: Request) {
  try {
    const {
      token,
      repoName: inputRepoName,
      branchName: inputBranchName = "main",
      commitMessage = "feat: sync template code tree from OpenVSCode IDE",
      isPrivate = false,
      treeData = [],
    } = await req.json();

    if (!token || !inputRepoName) {
      return NextResponse.json(
        { success: false, error: "GitHub PAT Token and Repository Name are required." },
        { status: 400 }
      );
    }

    const cleanToken = token.trim();
    const targetBranch = inputBranchName.trim() || "main";

    try {
      const { db } = await connectToDatabase();
      await db.collection("github_credentials").updateOne(
        { key: "active_token" },
        {
          $set: {
            key: "active_token",
            token: cleanToken,
            repoName: inputRepoName.trim(),
            branchName: targetBranch,
            isPrivate,
            updatedAt: new Date(),
          },
        },
        { upsert: true }
      );
    } catch {}

    const authHeaders = {
      Authorization: `bearer ${cleanToken}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent": "Pipeline-Management-IDE",
    };

    const userRes = await fetch("https://api.github.com/user", { headers: authHeaders });
    if (!userRes.ok) {
      const errText = await userRes.text();
      return NextResponse.json(
        { success: false, error: `Invalid GitHub Token: ${userRes.status} ${errText}` },
        { status: 401 }
      );
    }
    const userData = await userRes.json();
    const authenticatedUser = userData.login;

    let owner = authenticatedUser;
    let actualRepo = inputRepoName.trim();
    if (actualRepo.includes("/")) {
      const parts = actualRepo.split("/");
      owner = parts[0];
      actualRepo = parts[1];
    }

    const repoCheckRes = await fetch(`https://api.github.com/repos/${owner}/${actualRepo}`, {
      headers: authHeaders,
    });

    let repoCreated = false;
    let repoUrl = `https://github.com/${owner}/${actualRepo}`;

    if (repoCheckRes.status === 404) {
      const createRepoRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: authHeaders,
        body: JSON.stringify({
          name: actualRepo,
          private: isPrivate,
          auto_init: true,
          description: "Generated by Pipeline Management OpenVSCode IDE",
        }),
      });

      if (!createRepoRes.ok) {
        const createErr = await createRepoRes.text();
        return NextResponse.json(
          { success: false, error: `Failed to create GitHub repo: ${createErr}` },
          { status: 500 }
        );
      }

      const createData = await createRepoRes.json();
      repoUrl = createData.html_url || repoUrl;
      repoCreated = true;
      await new Promise((resolve) => setTimeout(resolve, 1500));
    } else if (repoCheckRes.ok) {
      const existingRepo = await repoCheckRes.json();
      repoUrl = existingRepo.html_url || repoUrl;
    }

    let filesToCommit = flattenTreeItems(treeData);
    if (filesToCommit.length === 0) {
      filesToCommit = [
        {
          path: "README.md",
          content: `# ${actualRepo}\n\nGenerated by OpenVSCode Pipeline Management IDE.`,
        },
      ];
    }

    const branchRes = await fetch(
      `https://api.github.com/repos/${owner}/${actualRepo}/branches/${targetBranch}`,
      { headers: authHeaders }
    );

    let baseCommitSha: string | null = null;
    let baseTreeSha: string | null = null;

    if (branchRes.ok) {
      const branchData = await branchRes.json();
      baseCommitSha = branchData.commit.sha;
      baseTreeSha = branchData.commit.commit.tree.sha;
    } else {
      const refsRes = await fetch(
        `https://api.github.com/repos/${owner}/${actualRepo}/git/matching-refs/heads/`,
        { headers: authHeaders }
      );
      if (refsRes.ok) {
        const refsData = await refsRes.json();
        if (Array.isArray(refsData) && refsData.length > 0) {
          baseCommitSha = refsData[0].object.sha;

          await fetch(`https://api.github.com/repos/${owner}/${actualRepo}/git/refs`, {
            method: "POST",
            headers: authHeaders,
            body: JSON.stringify({
              ref: `refs/heads/${targetBranch}`,
              sha: baseCommitSha,
            }),
          });
        }
      }
    }

    const treeEntries = filesToCommit.map((f) => ({
      path: f.path.replace(/^\/+/, ""),
      mode: "100644",
      type: "blob",
      content: f.content,
    }));

    const createTreeRes = await fetch(
      `https://api.github.com/repos/${owner}/${actualRepo}/git/trees`,
      {
        method: "POST",
        headers: authHeaders,
        body: JSON.stringify({
          base_tree: baseTreeSha || undefined,
          tree: treeEntries,
        }),
      }
    );

    if (!createTreeRes.ok) {
      const treeErr = await createTreeRes.text();
      return NextResponse.json(
        { success: false, error: `Failed to create Git Tree: ${treeErr}` },
        { status: 500 }
      );
    }
    const newTree = await createTreeRes.json();

    const createCommitRes = await fetch(
      `https://api.github.com/repos/${owner}/${actualRepo}/git/commits`,
      {
        method: "POST",
        headers: authHeaders,
        body: JSON.stringify({
          message: commitMessage,
          tree: newTree.sha,
          parents: baseCommitSha ? [baseCommitSha] : [],
        }),
      }
    );

    if (!createCommitRes.ok) {
      const commitErr = await createCommitRes.text();
      return NextResponse.json(
        { success: false, error: `Failed to create Git Commit: ${commitErr}` },
        { status: 500 }
      );
    }
    const newCommit = await createCommitRes.json();

    await fetch(
      `https://api.github.com/repos/${owner}/${actualRepo}/git/refs/heads/${targetBranch}`,
      {
        method: "PATCH",
        headers: authHeaders,
        body: JSON.stringify({
          sha: newCommit.sha,
          force: true,
        }),
      }
    );

    const shortHash = newCommit.sha.substring(0, 7);

    try {
      const { db } = await connectToDatabase();
      await db.collection("github_push_history").insertOne({
        shortHash,
        fullHash: newCommit.sha,
        subject: commitMessage,
        author: authenticatedUser,
        repoUrl: `${repoUrl}/tree/${targetBranch}`,
        repoName: `${owner}/${actualRepo}`,
        branchName: targetBranch,
        fileCount: filesToCommit.length,
        pushedAt: new Date(),
      });
    } catch {}

    const actionText = repoCreated
      ? `Repository '${actualRepo}' created on GitHub.`
      : `Synchronized with existing repository '${actualRepo}'.`;

    return NextResponse.json({
      success: true,
      repoUrl: `${repoUrl}/tree/${targetBranch}`,
      message: `${actionText} Committed and pushed all ${filesToCommit.length} workspace files to branch '${targetBranch}' (Commit SHA: ${shortHash}). PAT Token saved to MongoDB.`,
    });
  } catch (err: any) {
    return NextResponse.json(
      { success: false, error: err.message || "Failed to execute GitHub code sync." },
      { status: 500 }
    );
  }
}
