apiVersion: v1
kind: Service
metadata:
  name: gateway-traefik
  namespace: gateway
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: gateway-traefik
  type: LoadBalancer
