/**
 * ============================================================================
 * PRODUCTION COMBINATION STACK RULES ENGINE & SCRIPT GENERATOR
 * ============================================================================
 * Algorithm Flow:
 * 1. Preset Stack Catalog Resolution:
 *    - Full Observability Stack (Grafana, Prometheus, OTEL Collector, Loki, Tempo, Jaeger)
 *    - Kafka Streaming Stack (Zookeeper, Kafka, Schema Registry, Kafka UI)
 *    - Enterprise Database Hub (Postgres, Redis, MongoDB, ClickHouse)
 *    - Enterprise Search Stack (Elasticsearch, Kibana, Meilisearch)
 *    - API Gateway & Security Stack (Kong, Vault, Keycloak, Nginx)
 *    - AI Vector Knowledge Base Stack (Qdrant, Milvus, Weaviate, Chroma)
 * 2. Shell Script (`deploy-stack.sh`) Synthesis Engine:
 *    - Generates phase-ordered bash script with network creation & container health wait checks.
 * ============================================================================
 */

import { IMAGE_IDS } from "../constants/docker-lab.constants";
import { DOCKER_IMAGES_CATALOG } from "../domain/docker-images.catalog";
import type { ContainerConfig } from "../domain/entities/docker-image.entity";
import { resolveOrchestrationPlan, type OrchestratedStackPlan } from "./docker-orchestration.rules";

export interface ProductionStackPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
  badge: string;
  imageIds: string[];
}

export const PRODUCTION_STACK_PRESETS: ProductionStackPreset[] = [
  {
    id: "observability-stack",
    name: "Full Observability & Telemetry Suite",
    category: "Observability",
    description: "Production Grafana, Prometheus, OpenTelemetry Collector, Loki, Tempo, & Jaeger pipeline.",
    icon: "📊",
    badge: "Recommended",
    imageIds: [
      IMAGE_IDS.PROMETHEUS,
      IMAGE_IDS.LOKI,
      IMAGE_IDS.TEMPO,
      IMAGE_IDS.JAEGER,
      IMAGE_IDS.OPENTELEMETRY_COLLECTOR,
      IMAGE_IDS.GRAFANA,
    ],
  },
  {
    id: "kafka-streaming-stack",
    name: "Kafka Event-Driven Enterprise Bus",
    category: "Messaging",
    description: "Zookeeper cluster node, Kafka event broker, Schema Registry, & Kafka UI management dashboard.",
    icon: "⚡",
    badge: "Streaming",
    imageIds: [
      IMAGE_IDS.ZOOKEEPER,
      IMAGE_IDS.KAFKA,
      IMAGE_IDS.SCHEMA_REGISTRY,
      IMAGE_IDS.KAFKA_UI,
    ],
  },
  {
    id: "database-hub-stack",
    name: "High-Performance Polyglot Persistence",
    category: "Databases",
    description: "PostgreSQL relational engine, Redis in-memory cache, MongoDB document store, & ClickHouse analytics.",
    icon: "🚀",
    badge: "Enterprise",
    imageIds: [
      IMAGE_IDS.POSTGRES,
      IMAGE_IDS.REDIS,
      IMAGE_IDS.MONGODB,
      IMAGE_IDS.CLICKHOUSE,
    ],
  },
  {
    id: "search-analytics-stack",
    name: "Enterprise Search & Log Analytics",
    category: "Search",
    description: "Elasticsearch engine, Kibana visualizer, & Meilisearch fast vector search.",
    icon: "🔍",
    badge: "Analytics",
    imageIds: [
      IMAGE_IDS.ELASTICSEARCH,
      IMAGE_IDS.KIBANA,
      IMAGE_IDS.MEILISEARCH,
    ],
  },
  {
    id: "gateway-security-stack",
    name: "API Gateway & Security Zero-Trust Hub",
    category: "Security",
    description: "Kong API Gateway, HashiCorp Vault secrets manager, Keycloak IAM, & Nginx reverse proxy.",
    icon: "🌐",
    badge: "Zero-Trust",
    imageIds: [
      IMAGE_IDS.VAULT,
      IMAGE_IDS.KEYCLOAK,
      IMAGE_IDS.KONG,
      IMAGE_IDS.NGINX,
    ],
  },
  {
    id: "ai-vector-stack",
    name: "AI & Vector Embeddings Knowledge Base",
    category: "AI & Vector DBs",
    description: "Qdrant vector engine, Milvus vector database, & Weaviate neural search.",
    icon: "🤖",
    badge: "RAG & LLM",
    imageIds: [
      IMAGE_IDS.QDRANT,
      IMAGE_IDS.MILVUS,
      IMAGE_IDS.WEAVIATE,
      IMAGE_IDS.CHROMA,
    ],
  },
];

export function resolvePresetStackConfigs(presetId: string): ContainerConfig[] {
  const preset = PRODUCTION_STACK_PRESETS.find((p) => p.id === presetId);
  if (!preset) return [];
  return preset.imageIds
    .map((id) => DOCKER_IMAGES_CATALOG.find((img) => img.id === id)?.defaultConfig)
    .filter(Boolean) as ContainerConfig[];
}

export function generateDeployScript(plan: OrchestratedStackPlan): string {
  const lines: string[] = [];

  lines.push("#!/usr/bin/env bash");
  lines.push("# ============================================================================");
  lines.push("# PRODUCTION DOCKER LAB STACK DEPLOYMENT SCRIPT");
  lines.push("# Generated by Pipeline Management Rules Engine");
  lines.push("# ============================================================================");
  lines.push("set -euo pipefail\n");

  lines.push(`echo "🚀 Creating shared bridge network: ${plan.networkName}"`);
  lines.push(`docker network create ${plan.networkName} || true\n`);

  plan.phases.forEach((phase) => {
    lines.push(`echo "----------------------------------------------------------------------------"`);
    lines.push(`echo "▶ Launching ${phase.phaseName}"`);
    lines.push(`echo "----------------------------------------------------------------------------"`);

    phase.configs.forEach((cfg) => {
      const name = cfg.containerName || `${cfg.imageId}-node`;
      const alias = cfg.imageId;

      let portFlags = "";
      (cfg.ports || []).forEach((p) => {
        if (p.hostPort && p.containerPort) {
          portFlags += ` -p ${p.hostPort}:${p.containerPort}/${p.protocol || "tcp"}`;
        }
      });

      let envFlags = "";
      (cfg.envVars || []).forEach((e) => {
        if (e.key) {
          envFlags += ` -e "${e.key}=${e.value || ""}"`;
        }
      });

      const labelFlags = ` --label managed-by=infra-gateway-docker-lab --label image-id=${cfg.imageId}`;

      lines.push(`echo "  + Starting container: ${name} (${cfg.imageId}:${cfg.tag || "latest"})..."`);
      lines.push(`docker run -d --name ${name} --network ${plan.networkName} --network-alias ${alias}${portFlags}${envFlags}${labelFlags} ${cfg.imageId}:${cfg.tag || "latest"}`);
    });

    lines.push(`sleep 3\n`);
  });

  lines.push(`echo "============================================================================"`);
  lines.push(`echo "✅ All ${plan.orderedConfigs.length} stack containers launched successfully on network ${plan.networkName}!"`);
  lines.push(`echo "============================================================================"`);

  return lines.join("\n");
}
