apiVersion: v1
kind: Service
metadata:
  name: gateway-nginx
  namespace: gateway
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: gateway-nginx
  type: LoadBalancer
