import { DockerImageEntity, type DockerImage } from "./entities/docker-image.entity";
import { IMAGE_IDS, CATEGORIES } from "../constants/docker-lab.constants";

export const DOCKER_IMAGES_CATALOG: DockerImage[] = [
  DockerImageEntity.create({
    id: IMAGE_IDS.REDIS,
    name: "Redis Server",
    image: "redis",
    defaultTag: "7.2-alpine",
    category: CATEGORIES.DATABASES,
    description: "In-memory data structure store used as database, cache, streaming engine, and message broker.",
    icon: "🔴",
    defaultPort: 6379,
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.POSTGRES,
    name: "PostgreSQL",
    image: "postgres",
    defaultTag: "16-alpine",
    category: CATEGORIES.DATABASES,
    description: "Powerful, open source object-relational database system.",
    icon: "🐘",
    defaultPort: 5432,
    envVars: [
      { key: "POSTGRES_USER", value: "postgres" },
      { key: "POSTGRES_PASSWORD", value: "postgres" },
      { key: "POSTGRES_DB", value: "testdb" },
    ],
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.MYSQL,
    name: "MySQL Server",
    image: "mysql",
    defaultTag: "8.3",
    category: CATEGORIES.DATABASES,
    description: "World's most popular open source relational database management system.",
    icon: "🐬",
    defaultPort: 3306,
    envVars: [
      { key: "MYSQL_ROOT_PASSWORD", value: "root" },
      { key: "MYSQL_DATABASE", value: "testdb" },
    ],
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.MARIADB,
    name: "MariaDB Server",
    image: "mariadb",
    defaultTag: "11.3",
    category: CATEGORIES.DATABASES,
    description: "Community-developed, commercially supported fork of MySQL relational database.",
    icon: "🦭",
    defaultPort: 3306,
    envVars: [
      { key: "MARIADB_ROOT_PASSWORD", value: "root" },
      { key: "MARIADB_DATABASE", value: "testdb" },
    ],
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.MONGODB,
    name: "MongoDB Document DB",
    image: "mongo",
    defaultTag: "7.0-alpine",
    category: CATEGORIES.DATABASES,
    description: "General purpose, document-based, distributed database designed for modern apps.",
    icon: "🍃",
    defaultPort: 27017,
    envVars: [
      { key: "MONGO_INITDB_ROOT_USERNAME", value: "admin" },
      { key: "MONGO_INITDB_ROOT_PASSWORD", value: "password" },
    ],
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.INFLUXDB,
    name: "InfluxDB Time Series",
    image: "influxdb",
    defaultTag: "2.7-alpine",
    category: CATEGORIES.DATABASES,
    description: "Open-source time series database designed to handle high write and query loads.",
    icon: "📈",
    defaultPort: 8086,
    envVars: [
      { key: "DOCKER_INFLUXDB_INIT_MODE", value: "setup" },
      { key: "DOCKER_INFLUXDB_INIT_USERNAME", value: "admin" },
      { key: "DOCKER_INFLUXDB_INIT_PASSWORD", value: "password123" },
      { key: "DOCKER_INFLUXDB_INIT_ORG", value: "my-org" },
      { key: "DOCKER_INFLUXDB_INIT_BUCKET", value: "my-bucket" },
    ],
    healthProbe: { type: "http", port: 8086, path: "/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.CASSANDRA,
    name: "Apache Cassandra",
    image: "cassandra",
    defaultTag: "5.0",
    category: CATEGORIES.DATABASES,
    description: "Free and open-source distributed NoSQL database management system.",
    icon: "👁️",
    defaultPort: 9042,
    envVars: [{ key: "CASSANDRA_CLUSTER_NAME", value: "TestCluster" }],
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.COCKROACHDB,
    name: "CockroachDB",
    image: "cockroachdb/cockroach",
    defaultTag: "v23.2.3",
    category: CATEGORIES.DATABASES,
    description: "Cloud-native, distributed SQL database built on transactional key-value store.",
    icon: "🪳",
    defaultPort: 26257,
    healthProbe: { type: "http", port: 8080, path: "/health?ready=1" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.TIMESCALEDB,
    name: "TimescaleDB",
    image: "timescale/timescaledb",
    defaultTag: "latest-pg16",
    category: CATEGORIES.DATABASES,
    description: "Open-source time-series SQL database powered by PostgreSQL.",
    icon: "⏱️",
    defaultPort: 5432,
    envVars: [{ key: "POSTGRES_PASSWORD", value: "password" }],
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.SCYLLADB,
    name: "ScyllaDB NoSQL",
    image: "scylladb/scylla",
    defaultTag: "5.4",
    category: CATEGORIES.DATABASES,
    description: "C++ implementation of Apache Cassandra for ultra-low latency.",
    icon: "🐉",
    defaultPort: 9042,
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.SURREALDB,
    name: "SurrealDB Multi-Model",
    image: "surrealdb/surrealdb",
    defaultTag: "v1.3.0",
    category: CATEGORIES.DATABASES,
    description: "Ultimate multi-model database for web, mobile, serverless, jamstack, and traditional apps.",
    icon: "🌀",
    defaultPort: 8000,
    healthProbe: { type: "http", port: 8000, path: "/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.CLICKHOUSE,
    name: "ClickHouse Server",
    image: "clickhouse/clickhouse-server",
    defaultTag: "24.3-alpine",
    category: CATEGORIES.DATABASES,
    description: "Column-oriented database management system for real-time analytical reporting.",
    icon: "🏠",
    defaultPort: 8123,
    healthProbe: { type: "http", port: 8123, path: "/ping" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.NEO4J,
    name: "Neo4j Graph Database",
    image: "neo4j",
    defaultTag: "5.18-community",
    category: CATEGORIES.DATABASES,
    description: "Native graph database built to leverage data relationships.",
    icon: "🕸️",
    defaultPort: 7474,
    envVars: [{ key: "NEO4J_AUTH", value: "neo4j/password" }],
    healthProbe: { type: "http", port: 7474, path: "/" },
  }),

  DockerImageEntity.create({
    id: IMAGE_IDS.QDRANT,
    name: "Qdrant Vector DB",
    image: "qdrant/qdrant",
    defaultTag: "v1.8.2",
    category: CATEGORIES.AI_VECTOR,
    description: "Vector Similarity Search Engine with extended filtering support.",
    icon: "🎯",
    defaultPort: 6333,
    healthProbe: { type: "http", port: 6333, path: "/readyz" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.MILVUS,
    name: "Milvus Vector DB",
    image: "milvusdb/milvus",
    defaultTag: "v2.3.10",
    category: CATEGORIES.AI_VECTOR,
    description: "Open-source vector database built to power AI application and embeddings search.",
    icon: "⚡",
    defaultPort: 19530,
    healthProbe: { type: "http", port: 9091, path: "/healthz" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.WEAVIATE,
    name: "Weaviate Vector DB",
    image: "semitechnologies/weaviate",
    defaultTag: "1.24.8",
    category: CATEGORIES.AI_VECTOR,
    description: "Open source vector search engine with GraphQL & REST interface.",
    icon: "🧠",
    defaultPort: 8080,
    envVars: [
      { key: "AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED", value: "true" },
      { key: "PERSISTENCE_DATA_PATH", value: "/var/lib/weaviate" },
    ],
    healthProbe: { type: "http", port: 8080, path: "/v1/.well-known/ready" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.CHROMA,
    name: "Chroma Vector DB",
    image: "chromadb/chroma",
    defaultTag: "0.4.24",
    category: CATEGORIES.AI_VECTOR,
    description: "AI-native open-source embedding database for LLM apps.",
    icon: "🎨",
    defaultPort: 8000,
    healthProbe: { type: "http", port: 8000, path: "/api/v1/heartbeat" },
  }),

  DockerImageEntity.create({
    id: IMAGE_IDS.KAFKA,
    name: "Apache Kafka",
    image: "apache/kafka",
    defaultTag: "3.7.0",
    category: CATEGORIES.MESSAGING,
    description: "Distributed event streaming platform used for high-performance data pipelines.",
    icon: "🚀",
    defaultPort: 9092,
    envVars: [
      { key: "KAFKA_NODE_ID", value: "1" },
      { key: "KAFKA_PROCESS_ROLES", value: "broker,controller" },
      { key: "KAFKA_LISTENERS", value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093" },
      { key: "KAFKA_ADVERTISED_LISTENERS", value: "PLAINTEXT://localhost:9092" },
      { key: "KAFKA_CONTROLLER_QUORUM_VOTERS", value: "1@localhost:9093" },
      { key: "KAFKA_LISTEN_SECURITY_PROTOCOL_MAP", value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT" },
      { key: "KAFKA_CONTROLLER_LISTENER_NAMES", value: "CONTROLLER" },
      { key: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR", value: "1" },
      { key: "CLUSTER_ID", value: "MkU3OEVBNTcwNTJENDM2Qk" },
    ],
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.RABBITMQ,
    name: "RabbitMQ Broker",
    image: "rabbitmq",
    defaultTag: "3.13-management-alpine",
    category: CATEGORIES.MESSAGING,
    description: "Most widely deployed open source message broker supporting AMQP, MQTT, and STOMP.",
    icon: "🐇",
    defaultPort: 5672,
    envVars: [
      { key: "RABBITMQ_DEFAULT_USER", value: "guest" },
      { key: "RABBITMQ_DEFAULT_PASS", value: "guest" },
    ],
    healthProbe: { type: "http", port: 15672, path: "/api/health/checks/alarms" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.NATS,
    name: "NATS Server",
    image: "nats",
    defaultTag: "2.10-alpine",
    category: CATEGORIES.MESSAGING,
    description: "Simple, secure and high performance messaging system for cloud native applications.",
    icon: "⚡",
    defaultPort: 4222,
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.PULSAR,
    name: "Apache Pulsar",
    image: "apachepulsar/pulsar",
    defaultTag: "3.2.2",
    category: CATEGORIES.MESSAGING,
    description: "Distributed, open-source pub-sub messaging and streaming platform.",
    icon: "💫",
    defaultPort: 6650,
    healthProbe: { type: "http", port: 8080, path: "/admin/v2/clusters" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.ZOOKEEPER,
    name: "Apache ZooKeeper",
    image: "zookeeper",
    defaultTag: "3.9.2",
    category: CATEGORIES.MESSAGING,
    description: "Centralized service for maintaining configuration information and hierarchical key-value.",
    icon: "🐵",
    defaultPort: 2181,
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.SCHEMA_REGISTRY,
    name: "Confluent Schema Registry",
    image: "confluentinc/cp-schema-registry",
    defaultTag: "7.6.0",
    category: CATEGORIES.MESSAGING,
    description: "RESTful interface for storing and retrieving Avro, JSON, and Protobuf schemas.",
    icon: "📜",
    defaultPort: 8081,
    envVars: [
      { key: "SCHEMA_REGISTRY_HOST_NAME", value: "localhost" },
      { key: "SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS", value: "PLAINTEXT://localhost:9092" },
    ],
    healthProbe: { type: "http", port: 8081, path: "/subjects" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.KAFKA_UI,
    name: "Kafka UI",
    image: "provectuslabs/kafka-ui",
    defaultTag: "v0.7.1",
    category: CATEGORIES.MESSAGING,
    description: "Open-source web UI for managing Apache Kafka clusters.",
    icon: "🖥️",
    defaultPort: 8080,
    envVars: [
      { key: "KAFKA_CLUSTERS_0_NAME", value: "local" },
      { key: "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS", value: "localhost:9092" },
    ],
    healthProbe: { type: "http", port: 8080, path: "/actuator/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.MOSQUITTO,
    name: "Eclipse Mosquitto",
    image: "eclipse-mosquitto",
    defaultTag: "2.0-alpine",
    category: CATEGORIES.MESSAGING,
    description: "Lightweight open-source MQTT message broker suitable for IoT devices.",
    icon: "🦟",
    defaultPort: 1883,
  }),

  DockerImageEntity.create({
    id: IMAGE_IDS.GRAFANA,
    name: "Grafana Dashboards",
    image: "grafana/grafana",
    defaultTag: "10.4.1",
    category: CATEGORIES.OBSERVABILITY,
    description: "Open source visualization and analytics software for metrics, logs, and traces.",
    icon: "📊",
    defaultPort: 3000,
    envVars: [{ key: "GF_SECURITY_ADMIN_PASSWORD", value: "admin" }],
    healthProbe: { type: "http", port: 3000, path: "/api/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.PROMETHEUS,
    name: "Prometheus Monitoring",
    image: "prom/prometheus",
    defaultTag: "v2.51.1",
    category: CATEGORIES.OBSERVABILITY,
    description: "Open-source systems monitoring and alerting toolkit originally built at SoundCloud.",
    icon: "🔥",
    defaultPort: 9090,
    healthProbe: { type: "http", port: 9090, path: "/-/healthy" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.JAEGER,
    name: "Jaeger Tracing",
    image: "jaegertracing/all-in-one",
    defaultTag: "1.55",
    category: CATEGORIES.OBSERVABILITY,
    description: "Distributed tracing platform used for monitoring microservices transactions.",
    icon: "🐾",
    defaultPort: 16686,
    healthProbe: { type: "http", port: 16686, path: "/" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.TEMPO,
    name: "Grafana Tempo",
    image: "grafana/tempo",
    defaultTag: "2.4.0",
    category: CATEGORIES.OBSERVABILITY,
    description: "High-scale, easy-to-use distributed tracing backend.",
    icon: "⏳",
    defaultPort: 3200,
    healthProbe: { type: "http", port: 3200, path: "/ready" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.LOKI,
    name: "Grafana Loki",
    image: "grafana/loki",
    defaultTag: "2.9.6",
    category: CATEGORIES.OBSERVABILITY,
    description: "Like Prometheus, but for logs. Horizontally scalable log aggregation system.",
    icon: "🪵",
    defaultPort: 3100,
    healthProbe: { type: "http", port: 3100, path: "/ready" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.OPENTELEMETRY_COLLECTOR,
    name: "OpenTelemetry Collector",
    image: "otel/opentelemetry-collector-contrib",
    defaultTag: "0.96.0",
    category: CATEGORIES.OBSERVABILITY,
    description: "Vendor-agnostic proxy component for receiving, processing, and exporting telemetry data.",
    icon: "🔭",
    defaultPort: 4317,
    healthProbe: { type: "http", port: 13133, path: "/" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.ZIPKIN,
    name: "Zipkin Tracing",
    image: "openzipkin/zipkin",
    defaultTag: "3.0.4",
    category: CATEGORIES.OBSERVABILITY,
    description: "Distributed tracing system helps gather timing data needed to troubleshoot latency problems.",
    icon: "⚡",
    defaultPort: 9411,
    healthProbe: { type: "http", port: 9411, path: "/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.ALERTMANAGER,
    name: "Prometheus Alertmanager",
    image: "prom/alertmanager",
    defaultTag: "v0.27.0",
    category: CATEGORIES.OBSERVABILITY,
    description: "Handles alerts sent by client applications such as Prometheus.",
    icon: "🚨",
    defaultPort: 9093,
    healthProbe: { type: "http", port: 9093, path: "/-/healthy" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.VECTOR,
    name: "Timber Vector Agent",
    image: "timberio/vector",
    defaultTag: "0.36.0-alpine",
    category: CATEGORIES.OBSERVABILITY,
    description: "High-performance observability data pipeline written in Rust.",
    icon: "🏹",
    defaultPort: 8686,
    healthProbe: { type: "http", port: 8686, path: "/health" },
  }),

  DockerImageEntity.create({
    id: IMAGE_IDS.ELASTICSEARCH,
    name: "Elasticsearch Engine",
    image: "elasticsearch",
    defaultTag: "8.13.0",
    category: CATEGORIES.SEARCH,
    description: "Distributed, RESTful search and analytics engine capable of addressing real-time data.",
    icon: "🔎",
    defaultPort: 9200,
    envVars: [
      { key: "discovery.type", value: "single-node" },
      { key: "xpack.security.enabled", value: "false" },
    ],
    healthProbe: { type: "http", port: 9200, path: "/_cluster/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.KIBANA,
    name: "Kibana Visualizer",
    image: "kibana",
    defaultTag: "8.13.0",
    category: CATEGORIES.SEARCH,
    description: "Window into the Elastic Stack for visualizing Elasticsearch data.",
    icon: "📊",
    defaultPort: 5601,
    envVars: [{ key: "ELASTICSEARCH_HOSTS", value: "http://localhost:9200" }],
    healthProbe: { type: "http", port: 5601, path: "/api/status" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.OPENSEARCH,
    name: "OpenSearch Engine",
    image: "opensearchproject/opensearch",
    defaultTag: "2.12.0",
    category: CATEGORIES.SEARCH,
    description: "Open source distributed search and analytics suite derived from Elasticsearch.",
    icon: "🌐",
    defaultPort: 9200,
    envVars: [
      { key: "discovery.type", value: "single-node" },
      { key: "DISABLE_SECURITY_PLUGIN", value: "true" },
    ],
    healthProbe: { type: "http", port: 9200, path: "/" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.MEILISEARCH,
    name: "Meilisearch Engine",
    image: "getmeili/meilisearch",
    defaultTag: "v1.7.3",
    category: CATEGORIES.SEARCH,
    description: "Lightning-fast open-source search engine with out-of-the-box typo-tolerance.",
    icon: "⚡",
    defaultPort: 7700,
    envVars: [{ key: "MEILI_NO_ANALYTICS", value: "true" }],
    healthProbe: { type: "http", port: 7700, path: "/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.TYPESENSE,
    name: "Typesense Fast Search",
    image: "typesense/typesense",
    defaultTag: "0.25.2",
    category: CATEGORIES.SEARCH,
    description: "Open source, typo-tolerant search engine optimized for developer experience.",
    icon: "⚡",
    defaultPort: 8108,
    envVars: [
      { key: "TYPESENSE_DATA_DIR", value: "/tmp/typesense-data" },
      { key: "TYPESENSE_API_KEY", value: "xyz" },
    ],
    healthProbe: { type: "http", port: 8108, path: "/health" },
  }),

  DockerImageEntity.create({
    id: IMAGE_IDS.NGINX,
    name: "Nginx Reverse Proxy",
    image: "nginx",
    defaultTag: "1.25-alpine",
    category: CATEGORIES.PROXY,
    description: "High-performance HTTP server, reverse proxy, and IMAP/POP3 proxy server.",
    icon: "🟢",
    defaultPort: 80,
    healthProbe: { type: "http", port: 80, path: "/" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.TRAEFIK,
    name: "Traefik Proxy",
    image: "traefik",
    defaultTag: "v3.0",
    category: CATEGORIES.PROXY,
    description: "Modern HTTP reverse proxy and load balancer designed to deploy microservices.",
    icon: "🚦",
    defaultPort: 8080,
    healthProbe: { type: "http", port: 8080, path: "/ping" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.ENVOY,
    name: "Envoy Edge Proxy",
    image: "envoyproxy/envoy",
    defaultTag: "v1.29.2",
    category: CATEGORIES.PROXY,
    description: "Cloud-native high-performance edge/middle/service proxy.",
    icon: "🛡️",
    defaultPort: 10000,
    healthProbe: { type: "http", port: 10001, path: "/ready" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.HAPROXY,
    name: "HAProxy Load Balancer",
    image: "haproxy",
    defaultTag: "2.9-alpine",
    category: CATEGORIES.PROXY,
    description: "Reliable, high-performance TCP/HTTP load balancer.",
    icon: "⚖️",
    defaultPort: 80,
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.CADDY,
    name: "Caddy Web Server",
    image: "caddy",
    defaultTag: "2.7-alpine",
    category: CATEGORIES.PROXY,
    description: "Powerful, enterprise-ready open source web server with automatic HTTPS.",
    icon: "🔒",
    defaultPort: 80,
    healthProbe: { type: "http", port: 2019, path: "/config/" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.KONG,
    name: "Kong API Gateway",
    image: "kong",
    defaultTag: "3.6",
    category: CATEGORIES.PROXY,
    description: "Cloud-native API gateway and microservice management layer.",
    icon: "🦍",
    defaultPort: 8000,
    envVars: [{ key: "KONG_DATABASE", value: "off" }],
    healthProbe: { type: "http", port: 8001, path: "/status" },
  }),

  DockerImageEntity.create({
    id: IMAGE_IDS.VAULT,
    name: "HashiCorp Vault",
    image: "vault",
    defaultTag: "1.16",
    category: CATEGORIES.SECURITY,
    description: "Manage secrets and protect sensitive data in cloud infrastructure.",
    icon: "🔐",
    defaultPort: 8200,
    envVars: [{ key: "VAULT_DEV_ROOT_TOKEN_ID", value: "root" }],
    healthProbe: { type: "http", port: 8200, path: "/v1/sys/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.KEYCLOAK,
    name: "Keycloak Identity",
    image: "quay.io/keycloak/keycloak",
    defaultTag: "24.0.2",
    category: CATEGORIES.SECURITY,
    description: "Open source identity and access management for modern applications.",
    icon: "🔑",
    defaultPort: 8080,
    envVars: [
      { key: "KEYCLOAK_ADMIN", value: "admin" },
      { key: "KEYCLOAK_ADMIN_PASSWORD", value: "admin" },
    ],
    healthProbe: { type: "http", port: 8080, path: "/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.ORY_KRATOS,
    name: "Ory Kratos Identity",
    image: "oryd/kratos",
    defaultTag: "v1.1.0",
    category: CATEGORIES.SECURITY,
    description: "Headless user management and authentication system.",
    icon: "🐉",
    defaultPort: 4433,
    healthProbe: { type: "http", port: 4434, path: "/health/alive" },
  }),

  DockerImageEntity.create({
    id: IMAGE_IDS.MINIO,
    name: "MinIO Object Storage",
    image: "minio/minio",
    defaultTag: "RELEASE.2024-03-30T09-41-56Z",
    category: CATEGORIES.INFRASTRUCTURE,
    description: "High-performance S3-compatible object storage server.",
    icon: "🪣",
    defaultPort: 9000,
    envVars: [
      { key: "MINIO_ROOT_USER", value: "minioadmin" },
      { key: "MINIO_ROOT_PASSWORD", value: "minioadmin" },
    ],
    healthProbe: { type: "http", port: 9000, path: "/minio/health/live" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.JENKINS,
    name: "Jenkins Automation",
    image: "jenkins/jenkins",
    defaultTag: "lts-jdk17",
    category: CATEGORIES.INFRASTRUCTURE,
    description: "Leading open source automation server providing building, deploying and automating.",
    icon: "🤖",
    defaultPort: 8080,
    healthProbe: { type: "http", port: 8080, path: "/login" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.CONSUL,
    name: "HashiCorp Consul",
    image: "consul",
    defaultTag: "1.18",
    category: CATEGORIES.INFRASTRUCTURE,
    description: "Service networking solution to automate network configurations and discover services.",
    icon: "🌐",
    defaultPort: 8500,
    healthProbe: { type: "http", port: 8500, path: "/v1/status/leader" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.ETCD,
    name: "etcd Distributed KV",
    image: "bitnami/etcd",
    defaultTag: "3.5.12",
    category: CATEGORIES.INFRASTRUCTURE,
    description: "Strongly consistent, distributed key-value store used for Kubernetes state.",
    icon: "⚡",
    defaultPort: 2379,
    envVars: [{ key: "ALLOW_NONE_AUTHENTICATION", value: "yes" }],
    healthProbe: { type: "http", port: 2379, path: "/health" },
  }),
  DockerImageEntity.create({
    id: IMAGE_IDS.LOCALSTACK,
    name: "LocalStack Cloud Emulator",
    image: "localstack/localstack",
    defaultTag: "3.3.0",
    category: CATEGORIES.INFRASTRUCTURE,
    description: "Fully functional local AWS cloud stack developer emulator.",
    icon: "☁️",
    defaultPort: 4566,
    healthProbe: { type: "http", port: 4566, path: "/_localstack/health" },
  }),
];

export const DOCKER_IMAGE_REPOS: Record<string, string> = Object.fromEntries(
  DOCKER_IMAGES_CATALOG.map((img) => [img.id, img.image])
);

export const DOCKER_DEFAULT_TAGS: Record<string, string> = Object.fromEntries(
  DOCKER_IMAGES_CATALOG.map((img) => [img.id, img.defaultTag])
);

export const DOCKER_HUB_URLS: Record<string, string> = Object.fromEntries(
  DOCKER_IMAGES_CATALOG.map((img) => [img.id, img.officialUrl])
);
